<html>
<head>
<title><?php echo $title; ?></title>
<link rel="stylesheet" type="text/css" href="CSS/mystyle.css">
</head>
<body>

<h2>MySQLi Tutorial Examples - Example 2<h2>
<hr>
<h3>Execute a SELECT Query</h3>
<p>The query string is :- <code><?php echo $sql;?></code>

<h3>Resultset properties:</h3>
<ul>
<li>Rows Returned=<?php echo $rs->num_rows;?></li>
<li>Current Field Pointer=<?php echo $rs->current_field;?></li>
<li>Number of Fields=<?php echo $rs->field_count;?></li>
</ul>

<h3>Iterate Through Result Array</h3>
<?php  //$rs is the query resultset which is generated by the model
echo '<table border="1">';
foreach($rs as $row){
		echo '<tr><td>'.$row["StudentID"].'</td>';
		echo '<td>'.$row["FirstName"].'</td>';
		echo '<td>'.$row["LastName"].'</td>';
		echo '</tr>';
}
echo '</table>';
?>
<hr>
<a href="<?php echo $_SERVER["PHP_SELF"];?>">Home</a>
</body>
</html>
















 



