<html>
<head>
<title><?php echo $title; ?></title>
<link rel="stylesheet" type="text/css" href="CSS/mystyle.css">
</head>
<body>

<h2>MySQLi L01 Exercise<h2>
<hr>
<p>This view is the same as L01 Example 04  

<?php  //$rs is the query resultset which is generated by the model
//use the two resultsets to generate HTML tables
echo "<table border=1>";
//first - create the table caption and headings
echo "<caption>".strtoupper($table)." TABLE - QUERY RESULT</caption>";
echo '<tr>';
foreach($rs2 as $row) {
	echo '<th>'.$row['Field'].'</th>';
}
echo '</tr>';
	//then show the data
	foreach($rs1 as $row) {
		echo '<tr>';
		foreach($rs2 as $fieldName) {
			echo '<td>'.$row[$fieldName['Field']].'</td>';}
		echo '</tr>';
		}
echo "</table>";
echo "<br>";
?>
<hr>
<a href="<?php echo $_SERVER["PHP_SELF"];?>">Home</a>
</body>
</html>
















 



