<html>
<head>
<title><?php echo $title; ?></title>
<link rel="stylesheet" type="text/css" href="CSS/mystyle.css">
</head>
<body>

<h2>MySQLi Tutorial Examples - Example 3<h2>
<hr>
<p>This example stores the MySQL database connection parameters separately. 

<?php  //$rs is the query resultset which is generated by the model
echo '<table border="1">';
foreach($rs as $row){
		echo '<tr><td>'.$row["StudentID"].'</td>';
		echo '<td>'.$row["FirstName"].'</td>';
		echo '<td>'.$row["LastName"].'</td>';
		echo '</tr>';
}
echo '</table>';
?>
<hr>
<a href="<?php echo $_SERVER["PHP_SELF"];?>">Home</a>
</body>
</html>
















 



