<html>
<head>
<title><?php echo $title; ?></title>
<link rel="stylesheet" type="text/css" href="CSS/mystyle.css">
</head>
<body>

<h2>MySQLi Tutorial Examples - Example 4<h2>
<hr>
<p>This example dynamically generates a table with headings.

<?php  //$rs is the query resultset which is generated by the model
//use the two resultsets to generate HTML tables
echo "<table border=1>";
//first - create the table caption and headings
echo "<caption>".strtoupper($table)." TABLE - QUERY RESULT</caption>";
echo '<tr>';
foreach($rs2 as $row) { //$rs2 is a resultset that contains the headings
	echo '<th>'.$row['Field'].'</th>';
}
echo '</tr>';
	//then show the data
	foreach($rs1 as $row) {
		echo '<tr>';
		foreach($rs2 as $fieldName) { //$row["LectID"] this is the first $rs2, then FirstName, LastName, password according to the rows in the lecturer table
			echo '<td>'.$row[$fieldName['Field']].'</td>';} //extract the attribute for each of the columns
		echo '</tr>';
		}
echo "</table>";
echo "<br>";
?>
<hr>
<a href="<?php echo $_SERVER["PHP_SELF"];?>">Home</a>
</body>
</html>
